# fly.toml app configuration file generated for maj-webpage on 2023-10-11T10:59:33+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "maj-webpage"
primary_region = "waw"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
